name: 'Milestone Assigner'
description: 'Automatically add a Milestone to a Pull Request or Issue when opened'
author: 'Julexar'

branding:
  icon: tag
  color: blue

runs:
  using: 'node20'
  main: 'src/index.js'

inputs:
  token:
    description: 'GitHub Token'
    required: true
  milestone:
    description: 'Name of the Milestone or glob pattern'
    required: true
  use-glob:
    required: false
    default: 'false'
    description: 'Use the milestone as a regex pattern'
